import torch
from gpt_model import Character_GPT
import torch.nn as nn
from torch.nn import functional as F
from models import AttentionBlock as Attention
import math

"""
        Attention(Q, K, V) = softmax( M( Q @ K^T / sqrt(d_k) ) ) @ V
"""
# https://github.com/karpathy/minGPT/blob/master/mingpt/trainer.py 
# Section added to check CPU or GPU available by device ran.
device_setting = 'auto'
if device_setting == 'auto':
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
else:
    device = device_setting
print("running on device:", device)

'''Hyperparameters (estipulados por la rubrica)'''
BLOCK_SIZE = 64
LAYER_SIZE = 64
N_LAYERS = 2
LEARNING_RATE = 3e-4
MAX_ITERS = 3000
BATCH_SIZE = 32

'''Corpus Input/Read & Sort'''
with open('input.txt', 'r', encoding='utf-8') as corpus:
  # encodings posibles: utf-8, ascii
    text = corpus.read()

# self.embed = nn.Embedding(vocab_size, n_embd) de gpt_model.py
chars = set(text)
char_sort = sorted(list(chars))
vocab_size = len(char_sort)

# https://github.com/karpathy/nanoGPT/blob/master/data/shakespeare_char/prepare.py
# Section from nanoGPT, dictionaries para embed layer.
stoi = { ch:i for i,ch in enumerate(char_sort) }
itos = { i:ch for i,ch in enumerate(char_sort) }
def encode(s):
    return [stoi[c] for c in s] # encoder: take a string, output a list of integers
def decode(l):
    return ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string
  
data = torch.tensor(encode(text), dtype=torch.long)

'''Trainer Portion'''
def get_batch():
  # escoger un bloque aleatorio de training data para evitar overfitting.
    corpus_i = torch.randint(len(data) - BLOCK_SIZE, (BATCH_SIZE,))
    
    # a es input, b es conjunto para precision. 
    a = torch.stack([data[i : i + BLOCK_SIZE] for i in corpus_i])
    b = torch.stack([data[i + 1 : i + BLOCK_SIZE + 1] for i in corpus_i])
    return a.to(device), b.to(device)

print("Character-Level GPT init...")
model = Character_GPT(
    block_size=BLOCK_SIZE, 
    n_embd=LAYER_SIZE, 
    n_layer=N_LAYERS, 
    vocab_size=vocab_size
)
model = model.to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
print("training in progress...")
iter = 0
# https://github.com/karpathy/minGPT/blob/master/mingpt/trainer.py
while True:
    a, b = get_batch()
    loss = model.get_loss(a, b)
    optimizer.zero_grad(set_to_none=True) 
    loss.backward()                       
    optimizer.step()                

# The script prints a loss table every 300 steps..
    if iter % 300 == 0 or iter == MAX_ITERS - 1:
        print(f"Iteration/Step {iter:4d} | Loss: {loss.item():.4f}")
    iter += 1
    if iter >= MAX_ITERS:
        break
      
'''Text Sample Ending'''
# ..and generates a text sample at the end.
print("\nAutogenerated text sample:")
context = torch.zeros((1, 1), dtype=torch.long, device=device)
# model.generate() is from gpt_model.py
# https://github.com/karpathy/nanoGPT/blob/master/sample.py
sample = model.generate(context, max_new_tokens=300)[0].tolist()
print(decode(sample))
